### ISSUE TITLE
Error in Statamic 2.6

### ISSUE THREAD

**Issue by jamiedumont** [jrc9designstudio/statamic-video-embed#17]
Hi!

It looks like the way Statamic allows Addons to extend the functionality has subtly changed in 2.6. To quote their changelog: 

> "Your extra addon classes should longer extend Addon. Instead, you can should use the Extensible trait to get access to helper methods."

This is causing the following error:

```
Class Statamic\Addons\VideoEmbed\VideoEmbed may not inherit from final class (Statamic\Extend\Addon)
```

I'm not particularly proficient in php, otherwise I'd make what I'm sure is a simple change and submit a PR. Failing that, I thought I'd let you know what I've found!

Cheers, Jamie.

**Comment by jcohlmeyer** [comment]
Fixed. Let me know if you still have issues.

**Comment by jamiedumont** [comment]
Amazing, thanks! I managed to work it out myself, and monkey patched my site.

Was just about to submit a PR after hearing Jason confirm that the change I made was the proper way of doing it.

Cheers!
