### ISSUE TITLE
Doesn't appear to work with repeating fields

### ISSUE THREAD

**Issue by fitzage** [jrc9designstudio/statamic-video-embed#22]
I used the video embed field inside a grid field. When I enter a video URL in one row, it uses that same video URL in all the rows instead of each one keeping the video URL I put in it.

**Comment by fitzage** [comment]
Just tested with a standard replicator field and it does the same.

**Comment by jcohlmeyer** [comment]
I think this is actually this issue (with core Statamic) https://github.com/statamic/v2-hub/issues/1373

**Comment by jcohlmeyer** [comment]
@fitzage can you test [this commit](https://github.com/jrc9designstudio/statamic-video-embed/commit/977f4e4a60da0c1c33ecbf09a347af874b827bc9) out and see if this resolves the issue for you?

**Comment by fitzage** [comment]
Yes, perfect. Thanks!
