### ISSUE TITLE
Video meta data doesn't change with URL

### ISSUE THREAD

**Issue by jamiedumont** [jrc9designstudio/statamic-video-embed#8]
Hey, I think I may have found a bug, but can't be certain. 

I'm using a VideoEmbed field to pull in a YouTube video. This worked perfectly, and all the expected meta data came along with it.

I've since changed that video to a Vimeo one. The video itself changes, but all the other meta data (such as `title`, `description`, etc) remains the same as the data from the YouTube video.

It would appear to be because no meta data is coming from Vimeo on any of the videos I tested (both on my account and others), and it would also appear that the old meta data from the last video isn't removed, unless there is new data to take it's place.

I'll confess to not knowing PHP, so unfortunately can't help fix it, but thought I'd let you know.

Cheers for the awesome addon by the way!

**Comment by jcohlmeyer** [comment]
@jamiedumont most of the data is actually pulled in the Javascript in the vue component for the field at the moment. I am thinking of improving this so it will work better with Workshop.

I have made some changes to handle failed lookups better and will be releasing that soon.

Could you send me the YouTube and Vimeo urls that you tried and were having trouble with?

Also what version are you using?

Thanks for this feedback and helping me make the addon better :)

**Comment by jamiedumont** [comment]
Thanks for the quick response!

One of the Vimeo URLs I was having trouble with was this one: https://vimeo.com/205568957
However it seemed to be that meta data for any Vimeo video was unavailable.

I'm using the latest version of Statamic (2.5.7) and downloaded this repo yesterday.

**Comment by jcohlmeyer** [comment]
Interesting, I guess the settings on the video prevent the API from returning any information. I do not think there is much that I can do about that.

The new version of this repository should fix the issues of data not being reset when the lookup fails and show an error message to the user.

It also sets the video size to that of a 1080p video so aspect ratio media tags do not fail. I feel like this is a reasonable default if I can not look up the video size.
